
select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>(select avg(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as "Average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
count(*) as "Total Customers",
round(avg(purchase_amount),2) as "Average Spend", 
sum(purchase_amount) as "Total revenue"
from customer
group by subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
count(*) as total_sales,
count(case when discount_applied = 'Yes' then 1 end) as discounted_sales, 
round(count(case when discount_applied = 'Yes'then 1 end)*100/count(*),2) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 5


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select 
	case when previous_purchases<2 then 'New' 
		 when previous_purchases between 2 and 10 then 'Returning' 
		 when previous_purchases>10 then 'Loyal' 
	end as customer_segment,
	count(*) as "Number of customers"
from customer
group by customer_segment
order by "Number of customers" desc


--Q8. What are the top 3 most purchased products within each category? 
with item_counts as(
select item_purchased, category,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

--gemini
WITH product_ranks AS (
    SELECT 
        category, 
        item_purchased, 
        COUNT(*) AS purchase_count,
        DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) as rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT * FROM product_ranks
WHERE rank <= 3
ORDER BY category, rank;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 
select age_group,
Sum(purchase_amount) as revenue_generated
from customer
group by age_group
order by age_group desc





